"""Alter start_end

Revision ID: 5209847cc045
Revises: 9b5ad11c4aee
Create Date: 2022-06-22 04:17:02.788167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5209847cc045'
down_revision = '9b5ad11c4aee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workinghour_end_at'), 'workinghour', ['end_at'], unique=False)
    op.create_index(op.f('ix_workinghour_start_at'), 'workinghour', ['start_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workinghour_start_at'), table_name='workinghour')
    op.drop_index(op.f('ix_workinghour_end_at'), table_name='workinghour')
    # ### end Alembic commands ###
