"""empty message

Revision ID: 9b5ad11c4aee
Revises: 
Create Date: 2022-06-21 02:11:53.880649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5ad11c4aee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('full_name', sa.String(), nullable=True),
        sa.Column('category', sa.String(), nullable=True),
        sa.Column('consultation_fee', sa.Float(), nullable=True),
        sa.Column('language', sa.String(), nullable=True),
        sa.Column('district', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_category'), 'doctor', ['category'], unique=False)
    op.create_index(op.f('ix_doctor_district'), 'doctor', ['district'], unique=False)
    op.create_index(op.f('ix_doctor_full_name'), 'doctor', ['full_name'], unique=False)
    op.create_index(op.f('ix_doctor_id'), 'doctor', ['id'], unique=False)
    op.create_table('workinghour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.String(), nullable=True),
    sa.Column('end_at', sa.String(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workinghour_day'), 'workinghour', ['day'], unique=False)
    op.create_index(op.f('ix_workinghour_id'), 'workinghour', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workinghour_id'), table_name='workinghour')
    op.drop_index(op.f('ix_workinghour_day'), table_name='workinghour')
    op.drop_table('workinghour')
    op.drop_index(op.f('ix_doctor_id'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_full_name'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_district'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_category'), table_name='doctor')
    op.drop_table('doctor')
    # ### end Alembic commands ###
